# Generated by Django 5.0 on 2024-02-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_post_is_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_done',
            field=models.BooleanField(default=True, verbose_name='작성 완료'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_anonymous',
            field=models.BooleanField(default=False, verbose_name='익명 여부'),
        ),
    ]
