# Generated by Django 5.0 on 2024-02-06 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_post_is_done_alter_post_is_anonymous'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_done',
            new_name='is_draft',
        ),
    ]
