# Generated by Django 5.0 on 2024-02-07 15:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_rename_comment_comment_text_alter_comment_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookmark',
            new_name='PostBookmark',
        ),
        migrations.RenameModel(
            old_name='Like',
            new_name='PostLike',
        ),
    ]
