# Generated by Django 4.2.9 on 2024-01-24 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Main",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.TextField(max_length=3000)),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("교통사고", "교통사고"),
                            ("도난, 절도", "도난, 절도"),
                            ("실종신고", "실종신고"),
                            ("기타", "기타"),
                        ],
                        default="교통사고",
                        max_length=10,
                    ),
                ),
                (
                    "report",
                    models.CharField(
                        choices=[("찾아요", "찾아요"), ("제보해요", "제보해요")],
                        default="찾아요",
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
