# Generated by Django 4.2.9 on 2024-01-24 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="main",
            old_name="report",
            new_name="article",
        ),
    ]
