# Generated by Django 5.0 on 2024-02-13 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_rename_report_main_article"),
    ]

    operations = [
        migrations.CreateModel(
            name="MainComment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("writer", models.CharField(max_length=50)),
                ("content", models.TextField(max_length=300)),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="MainPost",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.TextField(max_length=3000)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("start_date", models.CharField(max_length=20)),
                ("end_date", models.CharField(max_length=20)),
                ("address", models.TextField(max_length=200)),
                ("latitude", models.CharField(max_length=10)),
                ("longtitude", models.CharField(max_length=10)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("교통사고", "교통사고"),
                            ("도난, 절도", "도난, 절도"),
                            ("실종신고", "실종신고"),
                            ("기타", "기타"),
                        ],
                        default="교통사고",
                        max_length=10,
                    ),
                ),
                (
                    "article",
                    models.CharField(
                        choices=[("찾아요", "찾아요"), ("제보해요", "제보해요")],
                        default="찾아요",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MainReply",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("writer", models.CharField(max_length=50)),
                ("content", models.TextField(max_length=300)),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Main",
        ),
        migrations.AddField(
            model_name="maincomment",
            name="mainpost",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="main.mainpost",
            ),
        ),
        migrations.AddField(
            model_name="mainreply",
            name="maincomment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="main.maincomment",
            ),
        ),
    ]
